### ISSUE TITLE
Process for running (missing files)

### ISSUE THREAD

**Issue by gundalow** [sandrotosi/ingresstools#1]
Hi,
I'm trying to run this locally where does `~/.tfl.json` come from or `data/london_m25_20160429041218_AllPortals.json`?

And are their any other notes you have have and I'll document this all.

Excellent tool :)

**Comment by sandrotosi** [comment]
it's described in the comment: `# store here the TfL API key info - 2 vars named app_id and app_key` so something like

```
{
    "app_id":  "XXX",
    "app_key": "XXX"
}
```

but you got to obtain the access key from the tfl website (else they limit you to 50 API calls per hr or sometihng similar)

**Comment by sandrotosi** [comment]
anyway, this is very london specific, and if you're interested in the results, they are published at: http://sandrotosi.me/ingress/london/tfl_bus_routes_maps.html

**Comment by gundalow** [comment]
Yup, planning some trips round London for the new 300 unique medal, I was going to raise some PRs for UI tweaks.

**Comment by gundalow** [comment]
Thanks for the details.
